#!/usr/bin/env bash
#
# Init the evrionment for new user.

set -eu

ACTIONS_WORKFLOW=pages-deploy.yml

TEMP_SUFFIX="to-delete" #  temporary file suffixes that make `sed -i` compatible with BSD and Linux


init_files() {
  if $_no_gh; then
    rm -rf .github
  else
    ## Change the files of `.github`
    mv .github/workflows/$ACTIONS_WORKFLOW.hook .
    rm -rf .github
    mkdir -p .github/workflows
    mv ./${ACTIONS_WORKFLOW}.hook .github/workflows/${ACTIONS_WORKFLOW}

    ## Cleanup image settings in site config
    sed -i.$TEMP_SUFFIX "s/^img_cdn:.*/img_cdn:/;s/^avatar:.*/avatar:/" _config.yml
    rm -f _config.yml.$TEMP_SUFFIX
  fi

  # trace the gem lockfile on user-end
  sed -i.$TEMP_SUFFIX "/Gemfile.lock/d" .gitignore
  rm -f ".gitignore.$TEMP_SUFFIX"

  # remove the other fies
  rm -rf _posts/*

  # save changes
  git add -A
  git commit -m "chore: initialize the environment" -q

  echo "[INFO] Initialization successful!"
}



_no_gh=false


init_files
